// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBchrUQznnq0FQpjInEkumcQT0VNQC1Nyw',
    appId: '1:678890602245:web:31016c',
    messagingSenderId: '678890602245',
    projectId: 'iot-prj-ac910',
    authDomain: 'iot-prj-ac910.firebaseapp.com',
    databaseURL: 'https://iot-prj-ac910-default-rtdb.firebaseio.com',
    storageBucket: 'iot-prj-ac910.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBchrUQznnq0FQpjInEkumcQT0VNQC1Nyw',
    appId: '1:678890602245:android:5c24a1cedf20440e31016c',
    messagingSenderId: '678890602245',
    projectId: 'iot-prj-ac910',
    databaseURL: 'https://iot-prj-ac910-default-rtdb.firebaseio.com',
    storageBucket: 'iot-prj-ac910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBchrUQznnq0FQpjInEkumcQT0VNQC1Nyw',
    appId: '1:678890602245:ios:31016c',
    messagingSenderId: '678890602245',
    projectId: 'iot-prj-ac910',
    databaseURL: 'https://iot-prj-ac910-default-rtdb.firebaseio.com',
    storageBucket: 'iot-prj-ac910.firebasestorage.app',
    iosBundleId: 'com.iotdevx.pill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBchrUQznnq0FQpjInEkumcQT0VNQC1Nyw',
    appId: '1:678890602245:macos:31016c',
    messagingSenderId: '678890602245',
    projectId: 'iot-prj-ac910',
    databaseURL: 'https://iot-prj-ac910-default-rtdb.firebaseio.com',
    storageBucket: 'iot-prj-ac910.firebasestorage.app',
    iosBundleId: 'com.iotdevx.pill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBchrUQznnq0FQpjInEkumcQT0VNQC1Nyw',
    appId: '1:678890602245:windows:31016c',
    messagingSenderId: '678890602245',
    projectId: 'iot-prj-ac910',
    authDomain: 'iot-prj-ac910.firebaseapp.com',
    databaseURL: 'https://iot-prj-ac910-default-rtdb.firebaseio.com',
    storageBucket: 'iot-prj-ac910.firebasestorage.app',
  );
}
